# Generated by Django 5.2.8 on 2025-12-23 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_on_trial',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='trial_ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='trial_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
